# Generated by Django 5.1.7 on 2025-04-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_service', '0002_alter_product_validity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
